import styled from "styled-components";
import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/Navbar";
import Sidebar from "../components/Sidebar";
import Footer from "../components/Footer";

import styles from "../styles/Home.module.css";
import { useState } from "react";
import HomeContent from "../components/HomeContent";

export default function Home() {
  const [identity, setIdentity] = useState();
  console.log("the identity valu is this");
  console.log(identity);
  return (
    <div>
      <Head>
        <title>joshua project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/** <Sidebar /> */}
      <Navbar />
      <HomeContent />
      <Footer />
    </div>
  );
}

const Wrapper = styled.div``;
